### ISSUE TITLE
Change main in bower.json

### ISSUE THREAD

**Issue by Sk1Zy** [stevenrskelton/flag-icon#3]
Would be nice if the main was set to the main files so this project can be used with [wiredep](https://github.com/taptapship/wiredep) to inject the required files into the html.

**Comment by stevenrskelton** [comment]
It's set to `flag-icon.html`, what else should it be set to?

I'm not familiar with the **wiredep** library, if there is a change you'd like please open a PR.

**Comment by Sk1Zy** [comment]
I made the mistake of thinking this was flag-icon-css when i posted this. It is set correctly as it is now.
